### ISSUE TITLE
latency issue in china

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/api-server#5]
## mainnet ping is bad (indonesia) https://api.sugarchain.org/

https://ping.chinaz.com/api.sugarchain.org
![image](https://user-images.githubusercontent.com/60179867/74079089-e8778f00-4a75-11ea-82aa-7e3a51e1af09.png)

## testnet ping is fine (japan) https://api-testnet.sugarchain.org/

https://ping.chinaz.com/api-testnet.sugarchain.org
![image](https://user-images.githubusercontent.com/60179867/74079092-ec0b1600-4a75-11ea-92f2-7101d3e7154a.png)

i suggest current singapore mainnet move location to japan or korea

**Comment by decryp2kanon** [comment]
@Rakutens

**Comment by volbil** [comment]
This issue not related to api server. Users in China should set up own api server for lower latency.

**Comment by decryp2kanon** [comment]
i guess we need more discuss. i can suggest following:
- upgrading VPS specs
- move VPS to Japan or another location
- users can select their API endpoint in Android Wallet (Web Wallet already) @obasys

**Comment by decryp2kanon** [comment]
TESTED at 23:00 (rush hour) in china

https://ping.chinaz.com/api-testnet.sugarchain.org
![image](https://user-images.githubusercontent.com/60179867/75163573-d3cc1400-5762-11ea-9629-7760b2dd0d7e.png)

https://ping.chinaz.com/api.sugarchain.org
![image](https://user-images.githubusercontent.com/60179867/75163705-0aa22a00-5763-11ea-9762-b3af6a15e387.png)

**Comment by decryp2kanon** [comment]
moved JP location
https://ping.chinaz.com/api.sugarchain.org
![image](https://user-images.githubusercontent.com/60179867/75654673-99530180-5ca3-11ea-8e41-d0699386d9e6.png)

**Comment by volbil** [comment]
Latest api server/mobile wallet updates essentially eliminated this issue.

**Comment by decryp2kanon** [comment]
FYI:
still `IPv6` not supported. but its fine.

- Testnet
![image](https://user-images.githubusercontent.com/60179867/75945699-5761cf80-5ede-11ea-87d8-3e7f10975af4.png)

- Mainnet
![image](https://user-images.githubusercontent.com/60179867/75945716-60eb3780-5ede-11ea-90a7-3e7cac5768cd.png)

Worldwide AVG ping API endpoint:
testnet: `180ms`
mainnet: `203ms`

https://www.dotcom-tools.com/ping-test.aspx
